### ISSUE TITLE
demo 提交后显示 nginx 404

### ISSUE THREAD

**Issue by keepthinkingit** [cczu-osa/pastebin#9]
问题 1: [demo](https://icpc.cczu.edu.cn/paste) 提交失败 , 是否正常 ?
问题 2: 使用此 [docker image](https://hub.docker.com/r/weicheng97/pastebin) 部署后也显示错误 . 

系统环境 : debian10 , 使用 nginx 反代 127.0.0.1:1003 可以正常显示页面 , 但是提交后直接重定向至 127.0.0.1 , 拒绝访问 .

**Comment by WeiCheng97** [comment]
@keepthinkingit 居然真的有人试图用

**Comment by WeiCheng97** [comment]
提交后这个是已知问题，待fix

**Comment by rewqazxv** [comment]
sorry, 反代需要加个设置, readme里没写

**Comment by keepthinkingit** [comment]
> sorry, 反代需要加个设置, readme里没写

坐等更新 readme   :)

**Comment by rewqazxv** [comment]
fix & thx

**Comment by rewqazxv** [comment]
> 问题 1: [demo](https://icpc.cczu.edu.cn/paste) 提交失败 , 是否正常 ?
> 问题 2: 使用此 [docker image](https://hub.docker.com/r/weicheng97/pastebin) 部署后也显示错误 .
> 
> 系统环境 : debian10 , 使用 nginx 反代 127.0.0.1:1003 可以正常显示页面 , 但是提交后直接重定向至 127.0.0.1 , 拒绝访问 .

反代问题不太清楚，有用域名吗

**Comment by keepthinkingit** [comment]
> > 问题 1: [demo](https://icpc.cczu.edu.cn/paste) 提交失败 , 是否正常 ?
> > 问题 2: 使用此 [docker image](https://hub.docker.com/r/weicheng97/pastebin) 部署后也显示错误 .
> > 系统环境 : debian10 , 使用 nginx 反代 127.0.0.1:1003 可以正常显示页面 , 但是提交后直接重定向至 127.0.0.1 , 拒绝访问 .
> 
> 反代问题不太清楚，有用域名吗

用的二级域名 , nginx 配置文件用的多站点虚拟主机 , 二级域名指向 127.0.0.1:1003 .

```
server
    {
        listen 443 ssl http2;
        server_name pastebin.xxx.xx;
        location / {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:1003;
            proxy_set_header X-Forwarded-Host    $host;
            proxy_set_header X-Forwarded-Port    $server_port;
        }
    }
```

**Comment by rewqazxv** [comment]
根据新readme设置一下baseurl应该就不会乱跳了

**Comment by keepthinkingit** [comment]
拉了新镜像 , 改配置后可以用了 , 真棒 , 非常感谢 ~
